mode = "dark"

accent = "#FF8800"
selection = "#FF8800"
muted = "#AABBCC"

background = "#0055AA"
dark_background = "#003388"
darker_background = "#001144"
lighter_background = "#0077CC"

foreground = "#FFFFFF"
dark_foreground = "#AABBCC"
light_foreground = "#FFFFFF"
bright_foreground = "#FFFFFF"

red = "#DD2222"
yellow = "#FFAA00"
orange = "#FF8800"
green = "#FFFFFF"
cyan = "#55AAAA"
blue = "#0055AA"
magenta = "#FF8800"
brown = "#AA5500"

bright_red = "#FF5555"
bright_yellow = "#FFCC00"
bright_green = "#FFFFFF"
bright_cyan = "#AACCFF"
bright_blue = "#55AAFF"
bright_magenta = "#FFAA55"

hyprland_active_border = "#FF8800"
hyprland_inactive_border = "#000000"
