[Icon Theme]
Name=Workbench 1.3
Comment=Kickstart 1.3 four-pen icons and cursors
Inherits=Yaru-blue,Yaru,Adwaita,hicolor
Directories=16x16/places,16x16/devices,16x16/mimetypes,16x16/status,24x24/places,24x24/devices,24x24/mimetypes,24x24/status,32x32/places,32x32/devices,32x32/mimetypes,32x32/status,48x48/places,48x48/devices,48x48/mimetypes,48x48/status,64x64/places,64x64/devices,64x64/mimetypes,64x64/status

[16x16/places]
Size=16
Context=Places
Type=Fixed

[16x16/devices]
Size=16
Context=Devices
Type=Fixed

[16x16/mimetypes]
Size=16
Context=Mimetypes
Type=Fixed

[16x16/status]
Size=16
Context=Status
Type=Fixed

[24x24/places]
Size=24
Context=Places
Type=Fixed

[24x24/devices]
Size=24
Context=Devices
Type=Fixed

[24x24/mimetypes]
Size=24
Context=Mimetypes
Type=Fixed

[24x24/status]
Size=24
Context=Status
Type=Fixed

[32x32/places]
Size=32
Context=Places
Type=Fixed

[32x32/devices]
Size=32
Context=Devices
Type=Fixed

[32x32/mimetypes]
Size=32
Context=Mimetypes
Type=Fixed

[32x32/status]
Size=32
Context=Status
Type=Fixed

[48x48/places]
Size=48
Context=Places
Type=Fixed

[48x48/devices]
Size=48
Context=Devices
Type=Fixed

[48x48/mimetypes]
Size=48
Context=Mimetypes
Type=Fixed

[48x48/status]
Size=48
Context=Status
Type=Fixed

[64x64/places]
Size=64
Context=Places
Type=Fixed

[64x64/devices]
Size=64
Context=Devices
Type=Fixed

[64x64/mimetypes]
Size=64
Context=Mimetypes
Type=Fixed

[64x64/status]
Size=64
Context=Status
Type=Fixed
